language: go
go:
  - 1.4
before_install:
  - go get github.com/alediaferia/stackgo
  - go get github.com/typeflow/triego
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - $HOME/gopath/bin/goveralls -repotoken ndnCqtzU2Y0ZMUKXLSfmIjbbWJvoaRpxV -service=travis-ci
